name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build static files
        run: |
          mkdir dist
          cp src/index.html dist/index.html
          cp src/style.css dist/style.css
          cp src/app.js dist/app.js
          cp -r files dist/files
          cp -r repo dist/repo
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
